server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  application:
    name: sprint-3-odontoprev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # datasource:
  #   url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
  #   username: rm552535
  #   password: 030804
  #   driver-class-name: oracle.jdbc.OracleDriver
  #   jpa:
  #     database-platform: org.hibernate.dialect.OracleDialect

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    initialize: true
    schema: classpath:schema.sql
    data: classpath:data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false

  devtools:
    restart:
      enabled: true

logging:
  level:
    root: INFO
    br: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
